" begin new Exception

:insert
throw new Exception("
.
